### ISSUE TITLE
get rid of whispering, replace it with "phone call"-like group creation behavior

### ISSUE THREAD

**Issue by kfinn** [kfinn/stoop#35]
when two memberships have been whispering to each other for a while (20 seconds?) auto-create a group for them

**Comment by samandmoore** [comment]
This is an interesting evolution. We tried auto-group on whisper-back and decided we didn't like it, but the time-based approach could be cool. Sorta like a proxy for the eye tracking idea / sorta like a new thing entirely. 

I'm curious what Kat thinks, but it would be cool to try it. Especially if there's a strong visual cue that you've been grouped up. 

I wonder if we would get some use out of a toast-style notification thing.

**Comment by kfinn** [comment]
updated this to match our Monday night meeting takeaways

**Comment by kfinn** [comment]
implemented in #38
